name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use the Node.js version your project requires

    - name: Install frontend dependencies
      run: npm ci

    - name: Build frontend assets
      run: npm run build

    - name: Set up testing environment
      run: cp .env.testing .env

    - name: Install PHP dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate application key
      run: php artisan key:generate

    - name: Set directory permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: /var/www/database/database.sqlite
      run: php artisan test --log-junit test-reports/junit.xml --coverage-clover test-reports/coverage.xml


    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: test-reports

    - name: Display Laravel logs on failure
      if: failure()
      run: cat storage/logs/laravel.log

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ps213073/deployment:latest

